import { useState } from "react";
import { Download } from "lucide-react";
import { Badge, PageHead, Table } from "@/features/intelligence/components/shared";

interface ExportRecord {
  id: string;
  report: string;
  module: "Finance" | "Sales" | "Commerce";
  format: "PDF" | "Excel";
  generatedBy: string;
  generatedAt: string;
  status: "ready" | "expired";
}

const initialExports: ExportRecord[] = [
  { id: "exp-1", report: "Quarter Post-Mortem — Q2", module: "Finance", format: "PDF", generatedBy: "Ada Okafor", generatedAt: "18 Jun 14:32", status: "ready" },
  { id: "exp-2", report: "Sales & Margin Report", module: "Sales", format: "Excel", generatedBy: "Ngozi Eze", generatedAt: "17 Jun 09:10", status: "ready" },
  { id: "exp-3", report: "Lender Brief", module: "Finance", format: "PDF", generatedBy: "Ada Okafor", generatedAt: "2 May 11:00", status: "expired" },
];

const filters = ["All", "Finance", "Sales", "Commerce", "PDF", "Excel"] as const;

export function ExportHistoryPage() {
  const [exports, setExports] = useState<ExportRecord[]>(initialExports);
  const [filter, setFilter] = useState<(typeof filters)[number]>("All");

  const filtered = exports.filter((record) => {
    if (filter === "All") return true;
    if (filter === "PDF" || filter === "Excel") return record.format === filter;
    return record.module === filter;
  });

  const regenerate = (id: string) => {
    setExports((current) => current.map((record) => (record.id === id ? { ...record, status: "ready", generatedAt: "just now" } : record)));
  };

  return (
    <div>
      <PageHead
        module="Reports"
        breadcrumb="Export History"
        title="Export History"
        description="Everything you've exported — re-download or re-generate expired files."
      />

      <div className="fi-chip-row" style={{ marginTop: 18 }}>
        {filters.map((label) => (
          <button
            type="button"
            key={label}
            className={`fi-chip ${filter === label ? "fi-chip-active" : ""}`}
            onClick={() => setFilter(label)}
          >
            {label}
          </button>
        ))}
      </div>

      {filtered.length === 0 ? (
        <div className="fi-empty fi-row-tight">
          <span className="fi-empty-icon">
            <Download size={18} strokeWidth={2.2} />
          </span>
          <h3>No exports yet</h3>
          <p>Generated PDFs and Excel files will appear here for re-download.</p>
        </div>
      ) : (
        <div className="fi-row-tight">
          <Table
            columns={[
              { key: "report", label: "Report" },
              { key: "format", label: "Format" },
              { key: "generatedBy", label: "Generated by" },
              { key: "generatedAt", label: "Generated at" },
              { key: "actions", label: "", align: "right" },
            ]}
            rows={filtered.map((record) => ({
              report: record.report,
              format: <Badge tone={record.format === "PDF" ? "danger" : "success"}>{record.format}</Badge>,
              generatedBy: record.generatedBy,
              generatedAt: record.generatedAt,
              actions:
                record.status === "expired" ? (
                  <span className="rpt-table-actions">
                    <span className="fi-stat-delta fi-stat-delta-down">Expired</span>
                    <button type="button" className="rpt-link" onClick={() => regenerate(record.id)}>
                      Re-generate
                    </button>
                  </span>
                ) : (
                  <button type="button" className="rpt-link">
                    Download
                  </button>
                ),
            }))}
            rowKey={(_row, index) => filtered[index]?.id ?? String(index)}
          />
        </div>
      )}
    </div>
  );
}
