/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as VRefRouteImport } from './routes/v/$ref'
import { Route as ConsentRequestTokenRouteImport } from './routes/consent-request.$token'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthResetRouteImport } from './routes/_auth.reset'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthOtpRouteImport } from './routes/_auth.otp'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthGetcodeRouteImport } from './routes/_auth.getcode'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppUploadIndexRouteImport } from './routes/_app/upload/index'
import { Route as AppSharesIndexRouteImport } from './routes/_app/shares/index'
import { Route as AppPortfolioIndexRouteImport } from './routes/_app/portfolio/index'
import { Route as AppNotificationsIndexRouteImport } from './routes/_app/notifications/index'
import { Route as AppMoneyIndexRouteImport } from './routes/_app/money/index'
import { Route as AppLendingIndexRouteImport } from './routes/_app/lending/index'
import { Route as AppInstitutionIndexRouteImport } from './routes/_app/institution/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppConsentIndexRouteImport } from './routes/_app/consent/index'
import { Route as AppCommerceIntelligenceIndexRouteImport } from './routes/_app/commerce-intelligence/index'
import { Route as AppAuditIndexRouteImport } from './routes/_app/audit/index'
import { Route as AppAccountsIndexRouteImport } from './routes/_app/accounts/index'
import { Route as AppAccountIndexRouteImport } from './routes/_app/account/index'

const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const VRefRoute = VRefRouteImport.update({
  id: '/v/$ref',
  path: '/v/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRequestTokenRoute = ConsentRequestTokenRouteImport.update({
  id: '/consent-request/$token',
  path: '/consent-request/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/_auth/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/_auth/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGetcodeRoute = AuthGetcodeRouteImport.update({
  id: '/_auth/getcode',
  path: '/getcode',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadIndexRoute = AppUploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => AppRoute,
} as any)
const AppSharesIndexRoute = AppSharesIndexRouteImport.update({
  id: '/shares/',
  path: '/shares/',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioIndexRoute = AppPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsIndexRoute = AppNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyIndexRoute = AppMoneyIndexRouteImport.update({
  id: '/money/',
  path: '/money/',
  getParentRoute: () => AppRoute,
} as any)
const AppLendingIndexRoute = AppLendingIndexRouteImport.update({
  id: '/lending/',
  path: '/lending/',
  getParentRoute: () => AppRoute,
} as any)
const AppInstitutionIndexRoute = AppInstitutionIndexRouteImport.update({
  id: '/institution/',
  path: '/institution/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppConsentIndexRoute = AppConsentIndexRouteImport.update({
  id: '/consent/',
  path: '/consent/',
  getParentRoute: () => AppRoute,
} as any)
const AppCommerceIntelligenceIndexRoute =
  AppCommerceIntelligenceIndexRouteImport.update({
    id: '/commerce-intelligence/',
    path: '/commerce-intelligence/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuditIndexRoute = AppAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/reports': typeof AppReportsRoute
  '/getcode': typeof AuthGetcodeRoute
  '/login': typeof AuthLoginRoute
  '/otp': typeof AuthOtpRoute
  '/register': typeof AuthRegisterRoute
  '/reset': typeof AuthResetRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/consent-request/$token': typeof ConsentRequestTokenRoute
  '/v/$ref': typeof VRefRoute
  '/about/': typeof AboutIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/account/': typeof AppAccountIndexRoute
  '/accounts/': typeof AppAccountsIndexRoute
  '/audit/': typeof AppAuditIndexRoute
  '/commerce-intelligence/': typeof AppCommerceIntelligenceIndexRoute
  '/consent/': typeof AppConsentIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/institution/': typeof AppInstitutionIndexRoute
  '/lending/': typeof AppLendingIndexRoute
  '/money/': typeof AppMoneyIndexRoute
  '/notifications/': typeof AppNotificationsIndexRoute
  '/portfolio/': typeof AppPortfolioIndexRoute
  '/shares/': typeof AppSharesIndexRoute
  '/upload/': typeof AppUploadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/reports': typeof AppReportsRoute
  '/getcode': typeof AuthGetcodeRoute
  '/login': typeof AuthLoginRoute
  '/otp': typeof AuthOtpRoute
  '/register': typeof AuthRegisterRoute
  '/reset': typeof AuthResetRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/consent-request/$token': typeof ConsentRequestTokenRoute
  '/v/$ref': typeof VRefRoute
  '/about': typeof AboutIndexRoute
  '/blog': typeof BlogIndexRoute
  '/contact': typeof ContactIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/terms': typeof TermsIndexRoute
  '/account': typeof AppAccountIndexRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/audit': typeof AppAuditIndexRoute
  '/commerce-intelligence': typeof AppCommerceIntelligenceIndexRoute
  '/consent': typeof AppConsentIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/institution': typeof AppInstitutionIndexRoute
  '/lending': typeof AppLendingIndexRoute
  '/money': typeof AppMoneyIndexRoute
  '/notifications': typeof AppNotificationsIndexRoute
  '/portfolio': typeof AppPortfolioIndexRoute
  '/shares': typeof AppSharesIndexRoute
  '/upload': typeof AppUploadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/_app/reports': typeof AppReportsRoute
  '/_auth/getcode': typeof AuthGetcodeRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/otp': typeof AuthOtpRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset': typeof AuthResetRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/consent-request/$token': typeof ConsentRequestTokenRoute
  '/v/$ref': typeof VRefRoute
  '/about/': typeof AboutIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_app/audit/': typeof AppAuditIndexRoute
  '/_app/commerce-intelligence/': typeof AppCommerceIntelligenceIndexRoute
  '/_app/consent/': typeof AppConsentIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/institution/': typeof AppInstitutionIndexRoute
  '/_app/lending/': typeof AppLendingIndexRoute
  '/_app/money/': typeof AppMoneyIndexRoute
  '/_app/notifications/': typeof AppNotificationsIndexRoute
  '/_app/portfolio/': typeof AppPortfolioIndexRoute
  '/_app/shares/': typeof AppSharesIndexRoute
  '/_app/upload/': typeof AppUploadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/reports'
    | '/getcode'
    | '/login'
    | '/otp'
    | '/register'
    | '/reset'
    | '/blog/$slug'
    | '/consent-request/$token'
    | '/v/$ref'
    | '/about/'
    | '/blog/'
    | '/contact/'
    | '/privacy/'
    | '/terms/'
    | '/account/'
    | '/accounts/'
    | '/audit/'
    | '/commerce-intelligence/'
    | '/consent/'
    | '/dashboard/'
    | '/institution/'
    | '/lending/'
    | '/money/'
    | '/notifications/'
    | '/portfolio/'
    | '/shares/'
    | '/upload/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/reports'
    | '/getcode'
    | '/login'
    | '/otp'
    | '/register'
    | '/reset'
    | '/blog/$slug'
    | '/consent-request/$token'
    | '/v/$ref'
    | '/about'
    | '/blog'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/account'
    | '/accounts'
    | '/audit'
    | '/commerce-intelligence'
    | '/consent'
    | '/dashboard'
    | '/institution'
    | '/lending'
    | '/money'
    | '/notifications'
    | '/portfolio'
    | '/shares'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/accept-invite'
    | '/_app/reports'
    | '/_auth/getcode'
    | '/_auth/login'
    | '/_auth/otp'
    | '/_auth/register'
    | '/_auth/reset'
    | '/blog/$slug'
    | '/consent-request/$token'
    | '/v/$ref'
    | '/about/'
    | '/blog/'
    | '/contact/'
    | '/privacy/'
    | '/terms/'
    | '/_app/account/'
    | '/_app/accounts/'
    | '/_app/audit/'
    | '/_app/commerce-intelligence/'
    | '/_app/consent/'
    | '/_app/dashboard/'
    | '/_app/institution/'
    | '/_app/lending/'
    | '/_app/money/'
    | '/_app/notifications/'
    | '/_app/portfolio/'
    | '/_app/shares/'
    | '/_app/upload/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AuthGetcodeRoute: typeof AuthGetcodeRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetRoute: typeof AuthResetRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ConsentRequestTokenRoute: typeof ConsentRequestTokenRoute
  VRefRoute: typeof VRefRoute
  AboutIndexRoute: typeof AboutIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$ref': {
      id: '/v/$ref'
      path: '/v/$ref'
      fullPath: '/v/$ref'
      preLoaderRoute: typeof VRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent-request/$token': {
      id: '/consent-request/$token'
      path: '/consent-request/$token'
      fullPath: '/consent-request/$token'
      preLoaderRoute: typeof ConsentRequestTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset': {
      id: '/_auth/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/otp': {
      id: '/_auth/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/getcode': {
      id: '/_auth/getcode'
      path: '/getcode'
      fullPath: '/getcode'
      preLoaderRoute: typeof AuthGetcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upload/': {
      id: '/_app/upload/'
      path: '/upload'
      fullPath: '/upload/'
      preLoaderRoute: typeof AppUploadIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shares/': {
      id: '/_app/shares/'
      path: '/shares'
      fullPath: '/shares/'
      preLoaderRoute: typeof AppSharesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio/': {
      id: '/_app/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof AppPortfolioIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications/': {
      id: '/_app/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AppNotificationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/money/': {
      id: '/_app/money/'
      path: '/money'
      fullPath: '/money/'
      preLoaderRoute: typeof AppMoneyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lending/': {
      id: '/_app/lending/'
      path: '/lending'
      fullPath: '/lending/'
      preLoaderRoute: typeof AppLendingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/institution/': {
      id: '/_app/institution/'
      path: '/institution'
      fullPath: '/institution/'
      preLoaderRoute: typeof AppInstitutionIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consent/': {
      id: '/_app/consent/'
      path: '/consent'
      fullPath: '/consent/'
      preLoaderRoute: typeof AppConsentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commerce-intelligence/': {
      id: '/_app/commerce-intelligence/'
      path: '/commerce-intelligence'
      fullPath: '/commerce-intelligence/'
      preLoaderRoute: typeof AppCommerceIntelligenceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit/': {
      id: '/_app/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AppAuditIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppReportsRoute: typeof AppReportsRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
  AppAuditIndexRoute: typeof AppAuditIndexRoute
  AppCommerceIntelligenceIndexRoute: typeof AppCommerceIntelligenceIndexRoute
  AppConsentIndexRoute: typeof AppConsentIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppInstitutionIndexRoute: typeof AppInstitutionIndexRoute
  AppLendingIndexRoute: typeof AppLendingIndexRoute
  AppMoneyIndexRoute: typeof AppMoneyIndexRoute
  AppNotificationsIndexRoute: typeof AppNotificationsIndexRoute
  AppPortfolioIndexRoute: typeof AppPortfolioIndexRoute
  AppSharesIndexRoute: typeof AppSharesIndexRoute
  AppUploadIndexRoute: typeof AppUploadIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppReportsRoute: AppReportsRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
  AppAuditIndexRoute: AppAuditIndexRoute,
  AppCommerceIntelligenceIndexRoute: AppCommerceIntelligenceIndexRoute,
  AppConsentIndexRoute: AppConsentIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppInstitutionIndexRoute: AppInstitutionIndexRoute,
  AppLendingIndexRoute: AppLendingIndexRoute,
  AppMoneyIndexRoute: AppMoneyIndexRoute,
  AppNotificationsIndexRoute: AppNotificationsIndexRoute,
  AppPortfolioIndexRoute: AppPortfolioIndexRoute,
  AppSharesIndexRoute: AppSharesIndexRoute,
  AppUploadIndexRoute: AppUploadIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AuthGetcodeRoute: AuthGetcodeRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetRoute: AuthResetRoute,
  BlogSlugRoute: BlogSlugRoute,
  ConsentRequestTokenRoute: ConsentRequestTokenRoute,
  VRefRoute: VRefRoute,
  AboutIndexRoute: AboutIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
