"""add accounts and bank_transactions tables

Revision ID: 13896e4093ec
Revises: 3318ce2cfa0c
Create Date: 2026-06-28 20:09:16.486503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13896e4093ec'
down_revision: Union[str, Sequence[str], None] = '2d04b5561778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('account_number_hash', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=True),
    sa.Column('statement_period_start', sa.Date(), nullable=True),
    sa.Column('statement_period_end', sa.Date(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('closing_balance', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('computed_closing_balance', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('balance_integrity_passed', sa.Boolean(), nullable=True),
    sa.Column('balance_discrepancy', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_number_hash'), 'accounts', ['account_number_hash'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payee_normalized', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('original_currency', sa.String(length=3), nullable=False),
    sa.Column('base_currency_amount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('type', sa.Enum('credit', 'debit', name='transactiontype'), nullable=False),
    sa.Column('mode', sa.Enum('bank_transfer', 'pos', 'cash_withdrawal', 'mobile_money', 'direct_debit', 'standing_order', 'bank_charge', name='transactionmode'), nullable=True),
    sa.Column('category', sa.Enum('income', 'operational_expense', 'personal', 'debt_service', 'interbank_transfer', 'tax', 'unknown', name='transactioncategory'), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('is_own_account_transfer', sa.Boolean(), nullable=False),
    sa.Column('is_anomalous', sa.Boolean(), nullable=False),
    sa.Column('fraud_flags', sa.JSON(), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('data_source', sa.Enum('gtbank_pdf', 'access_csv', 'zenith_pdf', 'opay_csv', 'generic_csv', 'generic_pdf', 'mono_api', name='banktransactiondatasource'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_account_id'), 'bank_transactions', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_transactions_account_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_number_hash'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###

    # On Postgres, op.create_table() implicitly ran CREATE TYPE for each Enum
    # column above; op.drop_table() does NOT drop those types, so re-upgrading
    # after this downgrade would fail with "type already exists" unless we
    # drop them explicitly here. SQLite has no CREATE/DROP TYPE at all, so
    # this is a no-op there.
    if op.get_bind().dialect.name == "postgresql":
        for enum_name in ("transactiontype", "transactionmode", "transactioncategory", "banktransactiondatasource"):
            op.execute(f"DROP TYPE IF EXISTS {enum_name}")
