"""add bank_account_identifiers table

Revision ID: 2d04b5561778
Revises: 54914b966989
Create Date: 2026-06-26 16:10:58.500620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d04b5561778'
down_revision: Union[str, Sequence[str], None] = '54914b966989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_account_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_number_hash', sa.String(), nullable=False),
    sa.Column('account_number_encrypted', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_number_hash', name='uq_user_account_hash')
    )
    op.create_index(op.f('ix_bank_account_identifiers_account_number_hash'), 'bank_account_identifiers', ['account_number_hash'], unique=False)
    op.create_index(op.f('ix_bank_account_identifiers_id'), 'bank_account_identifiers', ['id'], unique=False)
    op.create_index(op.f('ix_bank_account_identifiers_user_id'), 'bank_account_identifiers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_account_identifiers_user_id'), table_name='bank_account_identifiers')
    op.drop_index(op.f('ix_bank_account_identifiers_id'), table_name='bank_account_identifiers')
    op.drop_index(op.f('ix_bank_account_identifiers_account_number_hash'), table_name='bank_account_identifiers')
    op.drop_table('bank_account_identifiers')
    # ### end Alembic commands ###
