"""add error_message to uploads

Revision ID: 3135dec86355
Revises: bd5bd71257e0
Create Date: 2026-07-21 20:28:46.346413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3135dec86355'
down_revision: Union[str, Sequence[str], None] = '74b3becc9b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'error_message')
    # ### end Alembic commands ###
