"""add uploads table

Revision ID: 53577290017b
Revises: a1842ad3c5c3
Create Date: 2026-06-25 15:56:20.078235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53577290017b'
down_revision: Union[str, Sequence[str], None] = 'a1842ad3c5c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('analyzer_type', sa.Enum('ecommerce', 'sales', 'bank', name='analyzertype'), nullable=False),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('processing', 'ready', 'failed', name='uploadstatus'), nullable=False),
    sa.Column('rows_parsed', sa.Integer(), nullable=True),
    sa.Column('rows_rejected', sa.Integer(), nullable=True),
    sa.Column('date_range_start', sa.Date(), nullable=True),
    sa.Column('date_range_end', sa.Date(), nullable=True),
    sa.Column('days_of_history', sa.Integer(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_merchant_id'), 'uploads', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploads_merchant_id'), table_name='uploads')
    op.drop_table('uploads')
    # ### end Alembic commands ###

    # See task 1.20's docs for why this Postgres enum-type cleanup was
    # missing here; backfilled 2026-06-28. No-op on SQLite.
    #
    # NOTE: only drops `uploadstatus`, owned solely by this table — NOT
    # `analyzertype`, which `reconciliation_reports` and `contextual_markers`
    # also use. Dropping a shared type while other tables still reference it
    # fails on Postgres; `analyzertype` is only safe to drop in the baseline
    # migration's downgrade(), which runs last in a full downgrade-to-base
    # (after every table using it has already been dropped).
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TYPE IF EXISTS uploadstatus")
