"""add order_items table

Revision ID: 634749339e94
Revises: c5a01b2d2af9
Create Date: 2026-06-25 14:39:12.428961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634749339e94'
down_revision: Union[str, Sequence[str], None] = 'c5a01b2d2af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_cogs', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unit_shipping_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unit_return_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unit_net_margin', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_merchant_id'), 'order_items', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_sku'), 'order_items', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_sku'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_merchant_id'), table_name='order_items')
    op.drop_table('order_items')
    # ### end Alembic commands ###
