"""migrate_monetary_fields_to_integer

Revision ID: 84a26c480140
Revises: b1c4d7e2f3a8
Create Date: 2026-08-08 19:44:24.622026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a26c480140'
down_revision: Union[str, Sequence[str], None] = 'b1c4d7e2f3a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts') as batch_op:
        batch_op.alter_column( 'opening_balance',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    with op.batch_alter_table('accounts') as batch_op:
        batch_op.alter_column( 'closing_balance',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    with op.batch_alter_table('accounts') as batch_op:
        batch_op.alter_column( 'computed_closing_balance',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    with op.batch_alter_table('accounts') as batch_op:
        batch_op.alter_column( 'balance_discrepancy',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    with op.batch_alter_table('bank_transactions') as batch_op:
        batch_op.alter_column( 'amount',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=False)
    with op.batch_alter_table('bank_transactions') as batch_op:
        batch_op.alter_column( 'base_currency_amount',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    with op.batch_alter_table('bank_transactions') as batch_op:
        batch_op.alter_column( 'balance_after',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    with op.batch_alter_table('merchant_settings') as batch_op:
        batch_op.alter_column( 'default_return_cost',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    with op.batch_alter_table('order_items') as batch_op:
        batch_op.alter_column( 'unit_price',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=False)
    with op.batch_alter_table('order_items') as batch_op:
        batch_op.alter_column( 'unit_cogs',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    with op.batch_alter_table('order_items') as batch_op:
        batch_op.alter_column( 'unit_shipping_cost',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    with op.batch_alter_table('order_items') as batch_op:
        batch_op.alter_column( 'unit_return_cost',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    with op.batch_alter_table('order_items') as batch_op:
        batch_op.alter_column( 'unit_net_margin',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column( 'gross_revenue',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=False)
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column( 'base_currency_amount',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column( 'refund_amount',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column( 'discount_amount',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column( 'shipping_cost',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column( 'processing_fees',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column( 'allocated_ad_spend',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column( 'cogs',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column( 'net_margin',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    with op.batch_alter_table('payment_transactions') as batch_op:
        batch_op.alter_column( 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    with op.batch_alter_table('payment_transactions') as batch_op:
        batch_op.drop_constraint(op.f('uq_payment_transactions_provider_reference'), type_='unique')
    with op.batch_alter_table('subscriptions') as batch_op:
        batch_op.drop_constraint(op.f('uq_subscriptions_user_id'), type_='unique')
    with op.batch_alter_table('team_invites') as batch_op:
        batch_op.drop_constraint(op.f('uq_team_invites_token'), type_='unique')
    with op.batch_alter_table('uploads') as batch_op:
        batch_op.alter_column( 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('processing', 'ready', 'failed', 'needs_mapping', name='uploadstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads') as batch_op:
        batch_op.alter_column( 'status',
               existing_type=sa.Enum('processing', 'ready', 'failed', 'needs_mapping', name='uploadstatus'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    with op.batch_alter_table('team_invites') as batch_op:
        batch_op.create_unique_constraint(op.f('uq_team_invites_token'), ['token'])
    with op.batch_alter_table('subscriptions') as batch_op:
        batch_op.create_unique_constraint(op.f('uq_subscriptions_user_id'), ['user_id'])
    with op.batch_alter_table('payment_transactions') as batch_op:
        batch_op.create_unique_constraint(op.f('uq_payment_transactions_provider_reference'), ['provider_reference'])
    with op.batch_alter_table('payment_transactions') as batch_op:
        batch_op.alter_column( 'amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column( 'net_margin',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column( 'cogs',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column( 'allocated_ad_spend',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column( 'processing_fees',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column( 'shipping_cost',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column( 'discount_amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column( 'refund_amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column( 'base_currency_amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    with op.batch_alter_table('orders') as batch_op:
        batch_op.alter_column( 'gross_revenue',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=False)
    with op.batch_alter_table('order_items') as batch_op:
        batch_op.alter_column( 'unit_net_margin',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    with op.batch_alter_table('order_items') as batch_op:
        batch_op.alter_column( 'unit_return_cost',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    with op.batch_alter_table('order_items') as batch_op:
        batch_op.alter_column( 'unit_shipping_cost',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    with op.batch_alter_table('order_items') as batch_op:
        batch_op.alter_column( 'unit_cogs',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    with op.batch_alter_table('order_items') as batch_op:
        batch_op.alter_column( 'unit_price',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=False)
    with op.batch_alter_table('merchant_settings') as batch_op:
        batch_op.alter_column( 'default_return_cost',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    with op.batch_alter_table('bank_transactions') as batch_op:
        batch_op.alter_column( 'balance_after',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    with op.batch_alter_table('bank_transactions') as batch_op:
        batch_op.alter_column( 'base_currency_amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    with op.batch_alter_table('bank_transactions') as batch_op:
        batch_op.alter_column( 'amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=False)
    with op.batch_alter_table('accounts') as batch_op:
        batch_op.alter_column( 'balance_discrepancy',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    with op.batch_alter_table('accounts') as batch_op:
        batch_op.alter_column( 'computed_closing_balance',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    with op.batch_alter_table('accounts') as batch_op:
        batch_op.alter_column( 'closing_balance',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    with op.batch_alter_table('accounts') as batch_op:
        batch_op.alter_column( 'opening_balance',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
