"""add merchant_settings table

Revision ID: a1842ad3c5c3
Revises: 634749339e94
Create Date: 2026-06-25 15:04:11.909332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1842ad3c5c3'
down_revision: Union[str, Sequence[str], None] = '634749339e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=True),
    sa.Column('default_return_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('ad_kill_mode', sa.Enum('manual', 'auto', name='adkillmode'), nullable=False),
    sa.Column('ad_kill_threshold_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_settings_merchant_id'), 'merchant_settings', ['merchant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_settings_merchant_id'), table_name='merchant_settings')
    op.drop_table('merchant_settings')
    # ### end Alembic commands ###

    # See task 1.20's docs for why this Postgres enum-type cleanup was
    # missing here; backfilled 2026-06-28. No-op on SQLite.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TYPE IF EXISTS adkillmode")
