"""add analyzer_metadata to uploads table

Revision ID: a565fc6d6ec5
Revises: ece3007203c4
Create Date: 2026-07-06 01:42:28.130918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a565fc6d6ec5'
down_revision: Union[str, Sequence[str], None] = 'ece3007203c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('analyzer_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'analyzer_metadata')
    # ### end Alembic commands ###
