"""add owner_email to merchant_settings

Revision ID: c47facec5af1
Revises: 13896e4093ec
Create Date: 2026-06-29 23:13:32.061591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47facec5af1'
down_revision: Union[str, Sequence[str], None] = '13896e4093ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_settings', sa.Column('owner_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchant_settings', 'owner_email')
    # ### end Alembic commands ###
