"""add orders table

Revision ID: c5a01b2d2af9
Revises: 6aad96943bb2
Create Date: 2026-06-25 14:24:35.514598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a01b2d2af9'
down_revision: Union[str, Sequence[str], None] = '6aad96943bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('external_order_id', sa.String(), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gross_revenue', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('original_currency', sa.String(length=3), nullable=False),
    sa.Column('base_currency_amount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('exchange_rate_at_order', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('processing_fees', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('allocated_ad_spend', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('cogs', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('net_margin', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'fulfilled', 'refunded', 'cancelled', name='orderstatus'), nullable=False),
    sa.Column('data_source', sa.Enum('shopify_csv', 'woocommerce_csv', 'shopify_api', name='orderdatasource'), nullable=False),
    sa.Column('is_anomalous', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_merchant_id'), 'orders', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_merchant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###

    # On Postgres, op.create_table() implicitly ran CREATE TYPE for each Enum
    # column above; op.drop_table() does NOT drop those types, so re-upgrading
    # after this downgrade would fail with "type already exists" unless we
    # drop them explicitly here. SQLite has no CREATE/DROP TYPE at all, so
    # this is a no-op there. (Backfilled 2026-06-28 — see task 1.20's docs for
    # why this was missing here in the first place.)
    if op.get_bind().dialect.name == "postgresql":
        for enum_name in ("orderstatus", "orderdatasource"):
            op.execute(f"DROP TYPE IF EXISTS {enum_name}")
