"""add user_merchant_roles table

Revision ID: ce0027657e8f
Revises: c47facec5af1
Create Date: 2026-06-30 00:56:31.836836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0027657e8f'
down_revision: Union[str, Sequence[str], None] = 'c47facec5af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_merchant_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('vertical', sa.Enum('ecommerce', 'sales', 'bank', name='vertical'), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('rep_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'merchant_id', 'vertical', name='uq_user_merchant_vertical')
    )
    op.create_index(op.f('ix_user_merchant_roles_merchant_id'), 'user_merchant_roles', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_user_merchant_roles_user_id'), 'user_merchant_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_merchant_roles_user_id'), table_name='user_merchant_roles')
    op.drop_index(op.f('ix_user_merchant_roles_merchant_id'), table_name='user_merchant_roles')
    op.drop_table('user_merchant_roles')
    # ### end Alembic commands ###
    # op.create_table() implicitly runs CREATE TYPE for the 'vertical'
    # enum column, but op.drop_table() doesn't drop it -- must be explicit,
    # and only on Postgres (SQLite has no enum type at all).
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TYPE IF EXISTS vertical")
