"""add subscription_tier to users

Revision ID: ece3007203c4
Revises: 9f612082e573
Create Date: 2026-06-30 11:36:14.198018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece3007203c4'
down_revision: Union[str, Sequence[str], None] = 'ce0027657e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_tier', sa.String(), server_default='basic', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_tier')
    # ### end Alembic commands ###
